"""
SAP2 — Minimal Colab notebook (3 cells).
Generated by google_desk_app Send to Colab (run_app_sap2.bat).
"""

# CELL 1
from google.colab import auth, drive
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import os
import sys

CODE_FILE_ID = 'YOUR_CODE_FILE_ID_HERE'

print("=" * 60)
print("SAP2 — Human Matte + Normals (Sapiens2)")
print("=" * 60)
auth.authenticate_user()
drive_service = build('drive', 'v3')
code_path = '/content/cellcode.py'
request = drive_service.files().get_media(fileId=CODE_FILE_ID)
with open(code_path, 'wb') as f:
    downloader = MediaIoBaseDownload(f, request)
    done = False
    while not done:
        status, done = downloader.next_chunk()
        print(f"   Downloading cellcode: {int(status.progress() * 100)}%")
sys.path.insert(0, '/content')
with open(code_path, 'r', encoding='utf-8') as _cf:
    _head = _cf.read(4000)
if 'setup_sap2_cell1' not in _head:
    raise RuntimeError(
        'Wrong CODE_FILE_ID: file is not SAP2 cellcode. '
        'Re-run Send to Colab from google_desk_app (run_app_sap2.bat).'
    )
from cellcode import setup_sap2_cell1
drive_service = setup_sap2_cell1(drive_service)
print("\n[OK] Cell 1 complete.")


# CELL 2
CONFIG_FILE_ID = 'YOUR_CONFIG_FILE_ID_HERE'
from cellcode import load_sap2_config_cell2
config, drive_base_path, date_folder, logger, is_batch, config_path = load_sap2_config_cell2(
    drive_service, CONFIG_FILE_ID)
print(f"\n[OK] Config ready — batch={is_batch} shots={len(config.get('sequences') or [])}")


# CELL 3
from cellcode import process_sap2_cell3
_ok = process_sap2_cell3(
    config, drive_base_path, date_folder, logger, is_batch, config_path)
if _ok:
    print("\n[DONE] SAP2 batch complete.")
else:
    print(
        "\n[STOP] Cell 3 failed — scroll up for [ERROR] or "
        "'[sap2_colab_run] starting'. Re-run Cell 3 after fixing."
    )
